---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "crdb.cockroachlabs.com/v1alpha1",
          "kind": "CrdbCluster",
          "metadata": {
            "name": "crdb-tls-example"
          },
          "spec": {
            "tlsEnabled": true,
            "nodes": 3,
            "dataStore": {
              "pvc": {
                "spec": {
                  "accessModes": [
                    "ReadWriteOnce"
                  ],
                  "resources": {
                    "requests": {
                      "storage": "10Gi"
                    }
                  },
                  "volumeMode": "Filesystem"
                }
              }
            }
          }
        }
      ]
    capabilities: Full Lifecycle
    categories: Database
    certified: "true"
    containerImage: registry.connect.redhat.com/cockroachdb/cockroachdb-operator:v1.0.0-rc.4
    createdAt: 2020-09-03T19:29:26Z
    description: CockroachDB Operator
    repository: https://github.com/cockroachdb/cockroach-operator
    support: Cockroach Labs
  name: cockroach-operator.v1.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: CockroachDB is a Distributed SQL Database
        displayName: CockroachDB Cluster
        kind: CrdbCluster
        name: crdbclusters.crdb.cockroachlabs.com
        version: v1alpha1
        specDescriptors:
          - description: This field should always be empty
            displayName: DataStore
            path: dataStore
          - description: This flag determines the number of nodes that will be launched
            displayName: Nodes
            path: nodes
          - description: This flag determines if TLS is enabled for your CockroachDB Cluster
            displayName: TLS Enabled
            path: tlsEnabled
        statusDescriptors:
          - description: Status of the CrdbCluster resources
            displayName: Conditions
            path: conditions
            x-descriptors:
            - urn:alm:descriptor:io.kubernetes.conditions
          - description: Status of the CrdbCluster resources
            displayName: Operator Conditions
            path: operatorConditions
  description: This operator launches and manages a 3+ node cluster of CockroachDB.
  displayName: Cockroach Operator
  icon:
    - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMS44MiAzMiIgd2lkdGg9IjI0ODYiIGhlaWdodD0iMjUwMCI+PHRpdGxlPkNMPC90aXRsZT48cGF0aCBkPSJNMTkuNDIgOS4xN2ExNS4zOSAxNS4zOSAwIDAgMS0zLjUxLjQgMTUuNDYgMTUuNDYgMCAwIDEtMy41MS0uNCAxNS42MyAxNS42MyAwIDAgMSAzLjUxLTMuOTEgMTUuNzEgMTUuNzEgMCAwIDEgMy41MSAzLjkxek0zMCAuNTdBMTcuMjIgMTcuMjIgMCAwIDAgMjUuNTkgMGExNy40IDE3LjQgMCAwIDAtOS42OCAyLjkzQTE3LjM4IDE3LjM4IDAgMCAwIDYuMjMgMGExNy4yMiAxNy4yMiAwIDAgMC00LjQ0LjU3QTE2LjIyIDE2LjIyIDAgMCAwIDAgMS4xM2EuMDcuMDcgMCAwIDAgMCAuMDkgMTcuMzIgMTcuMzIgMCAwIDAgLjgzIDEuNTcuMDcuMDcgMCAwIDAgLjA4IDAgMTYuMzkgMTYuMzkgMCAwIDEgMS44MS0uNTQgMTUuNjUgMTUuNjUgMCAwIDEgMTEuNTkgMS44OCAxNy41MiAxNy41MiAwIDAgMC0zLjc4IDQuNDhjLS4yLjMyLS4zNy42NS0uNTUgMXMtLjIyLjQ1LS4zMy42OS0uMzEuNzItLjQ0IDEuMDhhMTcuNDYgMTcuNDYgMCAwIDAgNC4yOSAxOC43Yy4yNi4yNS41My40OS44MS43M3MuNDQuMzcuNjcuNTQuNTkuNDQuODkuNjRhLjA3LjA3IDAgMCAwIC4wOCAwYy4zLS4yMS42LS40Mi44OS0uNjRzLjQ1LS4zNS42Ny0uNTQuNTUtLjQ4LjgxLS43M2ExNy40NSAxNy40NSAwIDAgMCA1LjM4LTEyLjYxIDE3LjM5IDE3LjM5IDAgMCAwLTEuMDktNi4wOWMtLjE0LS4zNy0uMjktLjczLS40NS0xLjA5cy0uMjItLjQ3LS4zMy0uNjktLjM1LS42Ni0uNTUtMWExNy42MSAxNy42MSAwIDAgMC0zLjc4LTQuNDggMTUuNjUgMTUuNjUgMCAwIDEgMTEuNi0xLjg0IDE2LjEzIDE2LjEzIDAgMCAxIDEuODEuNTQuMDcuMDcgMCAwIDAgLjA4IDBxLjQ0LS43Ni44Mi0xLjU2YS4wNy4wNyAwIDAgMCAwLS4wOUExNi44OSAxNi44OSAwIDAgMCAzMCAuNTd6IiBmaWxsPSIjMTUxZjM0Ii8+PHBhdGggZD0iTTIxLjgyIDE3LjQ3YTE1LjUxIDE1LjUxIDAgMCAxLTQuMjUgMTAuNjkgMTUuNjYgMTUuNjYgMCAwIDEtLjcyLTQuNjggMTUuNSAxNS41IDAgMCAxIDQuMjUtMTAuNjkgMTUuNjIgMTUuNjIgMCAwIDEgLjcyIDQuNjgiIGZpbGw9IiMzNDg1NDAiLz48cGF0aCBkPSJNMTUgMjMuNDhhMTUuNTUgMTUuNTUgMCAwIDEtLjcyIDQuNjggMTUuNTQgMTUuNTQgMCAwIDEtMy41My0xNS4zN0ExNS41IDE1LjUgMCAwIDEgMTUgMjMuNDgiIGZpbGw9IiM3ZGJjNDIiLz48L3N2Zz4=
      mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
        - rules:
          - apiGroups:
            - security.openshift.io
            resources:
            - securitycontextconstraints
            resourceNames:
            - anyuid
            verbs:
            - use
          serviceAccountName: default
        - rules:
            - apiGroups:
                - "*"
              resources:
                - "*"
              verbs:
                - "*"
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterroles
              verbs:
                - get
                - list
                - delete
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - "*"
            - apiGroups:
                - apps
              resources:
                - statefulsets/finalizers
              verbs:
                - "*"
            - apiGroups:
                - apps
              resources:
                - statefulsets/status
              verbs:
                - "*"
            - apiGroups:
                - certificates.k8s.io
              resources:
                - certificatesigningrequests
              verbs:
                - "*"
            - apiGroups:
                - certificates.k8s.io
              resources:
                - certificatesigningrequests/approval
              verbs:
                - "*"
            - apiGroups:
                - certificates.k8s.io
              resources:
                - certificatesigningrequests/status
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - configmaps/status
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - pods/exec
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - services
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - services/finalizers
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - services/status
              verbs:
                - "*"
            - apiGroups:
                - crdb.cockroachlabs.com
              resources:
                - crdbclusters
              verbs:
                - "*"
            - apiGroups:
                - crdb.cockroachlabs.com
              resources:
                - crdbclusters/status
              verbs:
                - "*"
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - "*"
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets/finalizers
              verbs:
                - "*"
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets/status
              verbs:
                - "*"
            - verbs:
                - use
              apiGroups:
                - security.openshift.io
              resources:
                - securitycontextconstraints
              resourceNames:
                - anyuid
          serviceAccountName: cockroach-operator-role
      deployments:
        - name: cockroach-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: cockroach-operator
            strategy: {}
            template:
              metadata:
                labels:
                  app: cockroach-operator
              spec:
                containers:
                  - env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: cockroachdb
                      - name: RELATED_IMAGE_COCKROACH
                        value: "registry.connect.redhat.com/cockroachdb/cockroach:v20.1.5"
                    image: registry.connect.redhat.com/cockroachdb/cockroachdb-operator:v1.0.0-rc.4
                    imagePullPolicy: Always
                    name: cockroach-operator
                    resources:
                      requests:
                        cpu: 10m
                        memory: 32Mi
                serviceAccountName: cockroach-operator-role
    permissions:
      - rules:
          - apiGroups:
              - '*'
            resources:
              - '*'
            verbs:
              - '*'
        serviceAccountName: cockroach-operator-role
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - ""
  links:
    - name: Documentation
      url: https://docs.cockroachlabs.com
    - name: Operator Source
      url: https://github.com/cockroachdb/cockroach-operator
    - name: Cockroach Labs
      url: https://www.cockroachlabs.com
  maintainers:
    - email: support@cockroachlabs.com
      name: Cockroach Labs Support
  maturity: beta
  provider:
    name: Cockroach Labs
  version: 1.0.1